pipeline {
    agent sample-3
        
  
    stages {
        stage('Build') {
            steps {
               
		echo "executing build stage"
            }
        }
        stage('Test') {
            steps {
               	echo "executing test stage"

            }
            // post {
            //     always {
            //         junit 'target/surefire-reports/*.xml'
            //     }
            // }
        }
        stage('Deliver') {
            steps {
               	echo "executing delivery stage"
            }
        }
    }
}
