pipeline {
    agent {
                label 'mynode1'
            }
        
  
    stages {
        stage('Build') {
            steps {
                sh 'npm install'
                sh 'npm run build'
               
		echo "executing build stage"
            }
        }
        stage('Test') {
            steps {
                sh 'npm test'
               	echo "executing test stage"

            }
            // post {
            //     always {
            //         junit 'target/surefire-reports/*.xml'
            //     }
            // }
        }
        stage('Deliver') {
            steps {
                 sh 'npm run deploy'
               	echo "executing delivery stage"
            }
        }
    }
}
